name: Notion Repackage

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs: {}

env:
  NOTION_VERSION: 2.0.16
  NOTION_DOWNLOAD_HASH: 9f72284086cda3977f7f569dff3974d5
  NOTION_ENHANCER_COMMIT: b248ffa3bac393f267a4600d4e951aba8565f31e
  NOTION_REPACKAGED_REVISION: 1
  NOTION_REPACKAGED_DEBUG: true
  NOTION_REPACKAGED_REPO: https://github.com/jamezrin/tests-github-actions

jobs:
  make-vanilla-sources:
    name: Make vanilla sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download official Windows build
        run: scripts/download-exe.sh
      - name: Extract sources from Windows Build
        run: scripts/extract-src.sh
      - name: Zip sources dir with 7z
        working-directory: build
        run: 7z a vanilla-src.zip vanilla-src
      - name: Save vanilla sources as artifact
        uses: actions/upload-artifact@v2
        with:
          name: vanilla-sources
          path: build/vanilla-src.zip

  make-enhanced-sources:
    name: Make enhanced sources
    needs: [make-vanilla-sources]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve saved vanilla sources
        uses: actions/download-artifact@v2
        with:
          name: vanilla-sources
          path: build/vanilla-src.zip
      - name: Unzip sources with 7z
        working-directory: build
        run: 7z x vanilla-src.zip
      - name: Enhance extracted sources
        run: scripts/enhance-src.sh
      - name: Zip sources dir with 7z
        working-directory: build
        run: 7z a enhanced-src.zip enhanced-src
      - name: Save enhanced sources as artifact
        uses: actions/upload-artifact@v2
        with:
          name: enhanced-sources
          path: build/enhanced-src.zip

  build-app:
    name: Build app
    needs: [make-vanilla-sources, make-enhanced-sources]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [windows, linux, macos]
        edition: [vanilla, enhanced]
        include:
          - target: windows
            os: windows-latest
          - target: linux
            os: ubuntu-latest
          - target: macos
            os: macos-latest
          - edition: vanilla
            appName: Notion
          - edition: enhanced
            appName: Notion Enhanced
        exclude:
          - target: windows
            edition: vanilla
          - target: macos
            edition: vanilla
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Retrieve saved sources
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.edition }}-sources
          path: sources.zip
      - name: Unzip sources with 7z
        run: 7z x sources.zip
      - name: Install Linux build dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install --no-install-recommends -y libopenjp2-tools rpm libarchive-tools
      - name: Install dependencies
        working-directory: ${{ matrix.edition }}-src
        run: npm install
      - name: Run patch-package
        working-directory: ${{ matrix.edition }}-src
        run: node_modules/.bin/patch-package
      - name: Install electron and electron-builder
        working-directory: ${{ matrix.edition }}-src
        run: npm install electron@11 electron-builder --save-dev
      - name: Run electron-builder
        working-directory: ${{ matrix.edition }}-src
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          node_modules/.bin/electron-builder
          --${{ matrix.target }}
          -c.asar=${{ matrix.edition == 'vanilla' }}
          -c.productName="${{ matrix.appName }}"
          --config ../electron-builder.yaml

  cleanup:
    name: Cleanup artifacts
    if: always()
    needs: [build-app]
    strategy:
      matrix:
        edition: [vanilla, enhanced]
    runs-on: ubuntu-latest
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: '${{ matrix.edition }}-sources'
