name: Remove old artifacts

on:
  workflow_dispatch:
    inputs: {}

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          skip-recent: 1
          age: '1 hour'
